import test from 'node:test';
import assert from 'node:assert/strict';
import {emptyState,createCard,validateState,mergeBackup,rankRelated,relatedSuggestions,pairKey,makeAIRequest,parseAIResult,safeURL} from '../site/core.js';
const a=()=>createCard('想做一个让科研读文献更容易产生实验想法的工具。','','a');
const b=()=>createCard('每篇论文读完，记录一个还没被回答的问题，让文献阅读产生新的实验想法。','','b');
function fixture(){return {...emptyState(),cards:[a(),b(),createCard('周末去公园散步，观察树叶和天空。','','c')]};}
function answer(bundle){return {requestId:bundle.request.requestId,cardId:'a',title:'把文献阅读变成实验线索',tags:['科研'],nextStep:'记录一个未被回答的问题',relations:[{candidateId:'b',type:'可以一起推进',reason:'可以将文献中未回答的问题作为工具输入。',targetQuote:'实验想法',candidateQuote:'实验想法'}]};}
test('preserves original wording and rejects dangerous source links',()=>{const raw='别把“可能”整理成“已经证实”。';assert.equal(createCard(raw).raw,raw);assert.equal(safeURL('javascript:alert(1)'),'');assert.throws(()=>createCard(raw,'javascript:alert(1)'));assert.throws(()=>createCard('   '));});
test('related suggestions distinguish positive and unrelated examples',()=>{const s=fixture();const ranked=rankRelated(s.cards[0],s.cards);assert.equal(ranked[0].card.id,'b');assert(!ranked.some(item=>item.card.id==='c'));assert(ranked[0].reason.includes('实验想法'));});
test('confirmed and dismissed pairs are excluded in both directions',()=>{const s=fixture();s.dismissed=[pairKey('a','b')];assert.equal(relatedSuggestions(s.cards[0],s).length,0);assert.equal(relatedSuggestions(s.cards[1],s).length,0);s.dismissed=[];s.links=[{a:'a',b:'b',type:'同一个问题',reason:'',createdAt:new Date().toISOString()}];assert.equal(relatedSuggestions(s.cards[0],s).length,0);});
test('backup merge is idempotent and keeps current edits',()=>{const s=fixture(),incoming=structuredClone(s);incoming.cards[0].title='旧标题';s.cards[0].title='当前标题';const merged=mergeBackup(s,incoming);assert.equal(merged.cards.length,3);assert.equal(merged.cards[0].title,'当前标题');assert.deepEqual(mergeBackup(merged,incoming),merged);});
test('backup rejects dangling links and duplicate IDs',()=>{const s=fixture();s.links=[{a:'a',b:'missing',type:'同一个问题',reason:'',createdAt:new Date().toISOString()}];assert.throws(()=>validateState(s));const duplicate=fixture();duplicate.cards.push(a());assert.throws(()=>validateState(duplicate));});
test('AI result accepts an evidenced relation, preserves raw, and never auto-confirms it',()=>{const s=fixture(),bundle=makeAIRequest(s.cards[0],s,'request-1');const parsed=parseAIResult('```json\n'+JSON.stringify(answer(bundle))+'\n```',bundle.request,s);Object.assign(s.cards[0],parsed);assert.equal(s.cards[0].raw,a().raw);assert.equal(s.links.length,0);assert.equal(validateState(s).cards[0].aiSuggestions[0].candidateId,'b');});
test('AI rejects wrong requests, fabricated quotes, unknown candidates and stale cards',()=>{const s=fixture(),bundle=makeAIRequest(s.cards[0],s,'request-1');const wrong=answer(bundle);wrong.requestId='other';assert.throws(()=>parseAIResult(JSON.stringify(wrong),bundle.request,s));const fabricated=answer(bundle);fabricated.relations[0].targetQuote='没有出现的字';assert.throws(()=>parseAIResult(JSON.stringify(fabricated),bundle.request,s));const unknown=answer(bundle);unknown.relations[0].candidateId='c';assert.throws(()=>parseAIResult(JSON.stringify(unknown),bundle.request,s));s.cards[0].title='修改后的标题';assert.throws(()=>parseAIResult(JSON.stringify(answer(bundle)),bundle.request,s));});
test('AI allows no related cards and rejects malformed result',()=>{const s={...emptyState(),cards:[a()]},bundle=makeAIRequest(s.cards[0],s,'request-2'),result=answer(bundle);result.relations=[];assert.equal(parseAIResult(JSON.stringify(result),bundle.request,s).aiSuggestions.length,0);assert.throws(()=>parseAIResult('一段解释文字',bundle.request,s));});
