import assert from 'node:assert/strict';
import {mkdir,writeFile} from 'node:fs/promises';
import {pathToFileURL} from 'node:url';
import {createCard,STORAGE_KEY} from '../site/core.js';
const modulePath=process.env.PLAYWRIGHT_MODULE;if(!modulePath)throw new Error('Set PLAYWRIGHT_MODULE to an existing Playwright module; no project install is required.');
const {chromium}=await import(pathToFileURL(modulePath).href);
const browser=await chromium.launch({headless:true});
const origin=process.env.CHECK_URL||'http://127.0.0.1:4173/';
await mkdir(new URL('../test-results/',import.meta.url),{recursive:true});
const errors=[],failures=[];
try{
 const context=await browser.newContext({viewport:{width:1440,height:1100},acceptDownloads:true});const page=await context.newPage();page.on('pageerror',err=>errors.push(err.message));page.on('response',res=>{if(res.url().startsWith(origin)&&res.status()>=400)failures.push(`${res.status()} ${res.url()}`);});
 await page.goto(origin);await page.getByRole('button',{name:'加入示例，看看它如何工作'}).click();assert.equal(await page.locator('.idea-card').count(),3);
 await page.locator('#toast').waitFor({state:'hidden'});await page.screenshot({path:new URL('../test-results/desktop.png',import.meta.url).pathname.replace(/^\/([A-Z]:)/,'$1'),fullPage:true});
 await page.locator('.card-open').filter({hasText:'想做一个让科研'}).click();await page.getByRole('button',{name:'连起来',exact:true}).click();await page.getByRole('button',{name:'关闭详情',exact:true}).click();await page.locator('[data-view="connections"]').click();assert.equal(await page.locator('.connection-card').count(),1);
 await page.getByRole('button',{name:'撤销这条联系'}).click();assert.equal(await page.locator('.connection-card').count(),0);
 await page.locator('[data-view="inbox"]').click();await page.locator('#idea-input').fill('周末散步时，试着用照片记录三个忽略的小细节。');await page.getByRole('button',{name:'收下灵感'}).click();assert.equal(await page.locator('.idea-card').count(),4);
 await page.locator('#search').fill('三个忽略');assert.equal(await page.locator('.idea-card').count(),1);await page.locator('.card-open').click();await page.locator('#detail-title').fill('散步的观察练习');await page.getByRole('button',{name:'保存修改'}).click();await page.getByRole('button',{name:'归档',exact:true}).click();await page.locator('#search').fill('');await page.locator('[data-view="archive"]').click();assert.equal(await page.locator('.idea-card').count(),1);await page.locator('.card-open').click();await page.getByRole('button',{name:'恢复到收件箱'}).click();await page.locator('[data-view="inbox"]').click();assert.equal(await page.locator('.idea-card').count(),4);
 await page.locator('#settings-open').click();const downloadPromise=page.waitForEvent('download');await page.getByRole('button',{name:'导出备份'}).click();const download=await downloadPromise;assert(download.suggestedFilename().endsWith('.json'));const backup=await page.evaluate(key=>localStorage.getItem(key),STORAGE_KEY);await page.locator('#import-file').setInputFiles({name:'backup.json',mimeType:'application/json',buffer:Buffer.from(backup)});await page.getByRole('button',{name:'关闭使用说明'}).click();assert.equal(await page.locator('.idea-card').count(),4);
 // Network stub uses a fake key, never a provider account or real billing.
 let calls=0;await page.route('https://models.example.test/v1/chat/completions',async route=>{const req=route.request();if(req.method()==='OPTIONS'){await route.fulfill({status:204,headers:{'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'Authorization, Content-Type','Access-Control-Allow-Methods':'POST, OPTIONS'}});return;}calls++;const body=req.postDataJSON(),prompt=body.messages[0].content;let content='连接正常';if(prompt.includes('待分析数据：')){const data=JSON.parse(prompt.split('待分析数据：\n')[1]);content=JSON.stringify({requestId:data.requestId,cardId:data.idea.id,title:'模型整理的观察练习',tags:['生活'],nextStep:'下次散步记录一个细节',relations:[]});}await route.fulfill({status:200,headers:{'Access-Control-Allow-Origin':'*'},contentType:'application/json',body:JSON.stringify({choices:[{message:{content},finish_reason:'stop'}]})});});
 await page.locator('#model-open').click();await page.locator('#model-endpoint').fill('https://models.example.test/v1/chat/completions');await page.locator('#model-name').fill('personal-model');await page.locator('#model-key').fill('fake-browser-test-key');await page.getByRole('button',{name:'保存并测试'}).click();await page.locator('#model-config-status').filter({hasText:'连接验证成功'}).waitFor();assert.equal(await page.locator('#model-key').inputValue(),'');await page.getByRole('button',{name:'关闭模型连接'}).click();
 await page.locator('.card-open').filter({hasText:'散步的观察练习'}).click();await page.locator('#detail-ai').click();await page.locator('#call-model').click();await page.getByRole('button',{name:'确认更新卡片'}).waitFor();await page.getByRole('button',{name:'确认更新卡片'}).click();assert.equal(await page.locator('#detail-title').inputValue(),'模型整理的观察练习');assert((await page.locator('#detail-raw').innerText()).includes('三个忽略'));await page.getByRole('button',{name:'关闭详情',exact:true}).click();
 await page.locator('#model-open').click();await page.locator('#model-auto').check();await page.getByRole('button',{name:'保存本次连接'}).click();await page.locator('#idea-input').fill('记录三个忽略的小细节，持续观察周末散步的变化。');await page.getByRole('button',{name:'收下灵感'}).click();await page.locator('#auto-status').filter({hasText:'模型整理完成'}).waitFor();assert.equal(await page.locator('.idea-card').count(),5);
 const storage=await page.evaluate(()=>({local:JSON.stringify({...localStorage}),session:JSON.stringify({...sessionStorage})}));assert(!JSON.stringify(storage).includes('fake-browser-test-key'));assert(calls>=3);
 await page.reload();assert.equal(await page.locator('.idea-card').count(),5);assert.equal(await page.locator('#model-mode').innerText(),'本地整理');await page.locator('#model-open').click();assert.equal(await page.locator('#model-key').inputValue(),'');assert.equal(await page.locator('#model-auto').isChecked(),false);await page.getByRole('button',{name:'关闭模型连接'}).click();
 await page.evaluate(async()=>{await navigator.serviceWorker.ready;});await page.reload();await context.setOffline(true);await page.reload();await page.locator('#idea-input').fill('离线记录的想法仍然应该被保留。');await page.getByRole('button',{name:'收下灵感'}).click();assert.equal(await page.locator('.idea-card').count(),6);await context.setOffline(false);
 // Untrusted card text is rendered literally; it never becomes executable HTML.
 const malicious=createCard('<img src=x onerror="window.__bad=1"> 一段文字','','xss-test');await page.locator('#settings-open').click();const current=JSON.parse(await page.evaluate(key=>localStorage.getItem(key),STORAGE_KEY));current.cards.push(malicious);await page.locator('#import-file').setInputFiles({name:'untrusted.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(current))});await page.getByRole('button',{name:'关闭使用说明'}).click();assert.equal(await page.locator('.idea-card img').count(),0);assert.equal(await page.evaluate(()=>window.__bad),undefined);
 const mobile=await browser.newContext({viewport:{width:390,height:844},deviceScaleFactor:1,isMobile:true,hasTouch:true});const mobilePage=await mobile.newPage();mobilePage.on('pageerror',err=>errors.push(err.message));await mobilePage.goto(origin);await mobilePage.getByRole('button',{name:'加入示例，看看它如何工作'}).click();await mobilePage.locator('#settings-compact').click();await mobilePage.getByRole('button',{name:'导出备份'}).waitFor();await mobilePage.getByRole('button',{name:'关闭使用说明'}).click();const width=await mobilePage.evaluate(()=>({body:document.documentElement.scrollWidth,viewport:innerWidth}));assert(width.body<=width.viewport,JSON.stringify(width));await mobilePage.locator('#toast').waitFor({state:'hidden'});await mobilePage.screenshot({path:new URL('../test-results/mobile.png',import.meta.url).pathname.replace(/^\/([A-Z]:)/,'$1'),fullPage:true});await mobile.close();
 assert.deepEqual(errors,[]);assert.deepEqual(failures,[]);await writeFile(new URL('../test-results/browser-check.json',import.meta.url),JSON.stringify({checkedAt:new Date().toISOString(),origin,checks:['capture','keyword candidate','confirm/revoke','search','edit/raw preservation','archive/restore','backup roundtrip','mock model test','mock manual model','mock automatic model','key not persisted','reload resets model','offline capture','untrusted text','mobile width'],realProviderCall:false,errors,failures},null,2));console.log('Browser checks passed; mock responses only, no real model calls.');
}finally{await browser.close();}
